"""calendar

Revision ID: 1b6f3a35479a
Revises: 243b368a5844
Create Date: 2022-09-24 09:22:57.024845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6f3a35479a'
down_revision = '243b368a5844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('memodate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'memodate')
    # ### end Alembic commands ###
